### ISSUE TITLE
Error calling MCAS API. The exception was: {"detail":"Invalid user - the owner  of this token is not permitted to use tokens"}

### ISSUE THREAD

**Issue by alexverboon** [microsoft/MCAS#68]
Hello there, 

just created a new token and ran a script that had always worked, however we now get the following error. 

Error calling MCAS API. The exception was: {"detail":"Invalid user - the owner 
of this token is not permitted to use tokens"}

The token was created with a user that is global admin on the tenant.

**Comment by Javanite** [comment]
Hi @alexverboon ,

Usually when we see this error it's due to the token being created by user who does not have full permissions in MCAS. I see you mentioned that the user who created the token was a global admin, but could you please go to the "Manage Admin Access" section of the MCAS portal and verify that the user does not show up as a Security Reader? If you verified the user is a Security Admin or a Global Admin in MCAS, could you delete your old token and create a new one and try again and see if you have the same results. Screenshots are helpful too if you could share (redacting any sensitive info).

![image](https://user-images.githubusercontent.com/19479604/91892845-2e7d8580-ec48-11ea-960d-d8eb1e2d4bf7.png)

**Comment by Javanite** [comment]
Closed due to inactivity. If the issue persists, please re-open.
