### ISSUE TITLE
Increase number of application IDs returned by Get-MCASAppID

### ISSUE THREAD

**Issue by PaulBendall** [microsoft/MCAS#70]
Get-MCASAppID only returns a minuscule number of application IDs listed in MCAS. The application ID is needed to then use Get-MCASAppInfo. 

For example;

Slack is listed in the MCAS catalogue but you can't get the AppID using Get-MCASAppID and supplying the name Slack, it is not one of the applications listed in the array of applications. However, through some HTML page scraping, it is possible to work out the Slack AppID is 23043 - supplying this to Get-MCASAppInfo provides data on Slack which is available in the Catlogue.

**Comment by Javanite** [comment]
Hi @PaulBendall ,

Get-MCASAppId was originally designed as a utility cmdlet that simply does a lookup internal to the module to grab AppId's for api-connected apps. The proper way to get the list of appId's you are looking for is to use Get-MCASDiscoveredApp first, build a list of AppId's from those results, then pass that into Get-MCASAppInfo.

It might seem unnecessarily tedious to do it this way, but the reason is to prevent mass dumping of the App Catalog.

Here's an example of getting Security scores for 10 apps:


```
Get-MCASDiscoveredApp -StreamId 5c45cf5a78ccffdd8e99bb8a -ResultSetSize 10 -Tag Unsanctioned | `
Select-Object -ExpandProperty appId | Foreach-Object { Get-MCASAppInfo -AppId $_ -WarningAction SilentlyContinue | `
Select-Object @{N='App';E={$_.Name}}, @{N='Security Score';E = {[Math]::Round($_.revised_score.security)}}} | ` 
Format-Table -AutoSize

App                           Security Score
---                           --------------
AdMob                                      9
Twitter                                    8
HighTail                                   8
SugarSync                                  7
OpenDrive                                  8
TappIn                                     6
MediaFire                                  8
Otixo                                      7
Atlantic Metro Communications              7
weborama                                   7
```


Additionally, if there's just a specific AppId you are looking for, you can always grab it out of the URL bar in the console. Just go to the specific app page (via the Discovered Apps list) and you will see something like this:

`https://yourdomain.portal.cloudappsecurity.com/#/discovery/13979?tab=usage`

Where in this case, the appId is 13979.
