### ISSUE TITLE
Expose Property & Weight Scores for apps in the Cloud App Catalog

### ISSUE THREAD

**Issue by PaulBendall** [microsoft/MCAS#71]
In the UI it is possible to compare apps in the catalogue by the property, additionally hovering over the property will give the property score and associated weight. The information is not available using PowerShell cmdlet Get-MCASAppInfo.

![image](https://user-images.githubusercontent.com/22103900/79864280-1c095a80-83d1-11ea-9dd2-66bb36afaa39.png)

**Comment by Javanite** [comment]
Hi @PaulBendall ,

You can find category weights in the output of Get-MCASAppInfo in the riskFactors section. Under riskFactors, there are 4 numbers (0,1,2,3) which map to the different categories:

0 = Provider 
1 = Security 
2 = Compliance
3 = Legal

Within those categories, are the different metrics, such as ISO 27001. For each metric, there is an attribute called ScoreWeight which refers to your weighting choices in the console. 

0 = Ignored
1 = Low
2 = Medium (Default)
4 = High
8 = Very High


```
"riskFactors":  {
                        "2":  [
                                  {
                                      "id":  21,
                                      "title":  "ISO 27001",
                                      "value":  true,
                                      "displayType":  2,
                                      "hasComplexScoreField":  false,
                                      "possibleValues":  "Yes, No, N/A",
                                      "scoreWeight":  2,
                                      "source":  "Cloud analyst",
                                      "category":  2
```


In order to calculate "Weight in category" like you see in your screenshot, you would have to script that yourself by calculating ( 1 / N ) where N is the number of metrics in the category. In the below example, I am am calculating the Weight in Category for the security category, which returns **6** just like in your screenshot.

```
[MATH]::round(
    1 / `
        (Get-MCASDiscoveredApp -ResultSetSize 1 |`
        select -ExpandProperty riskfactors | select -ExpandProperty "1" |` 
        Where-Object {$null -ne $_.scoreWeight} |`
        Measure-Object |`
    select -ExpandProperty count) `
    * 100)

6
```
